NATIVE_LIB_OBJDIR=$(BUILD_DIR)/native_lib_obj

NATIVE_LIB_SRCDIR=native_lib
NATIVE_LIB_INCLUDEDIR=include

_NATIVE_LIB_OBJS+=print.o

NATIVE_CFLAGS+=-I$(NATIVE_LIB_INCLUDEDIR)

NATIVE_LIB_OBJS=$(foreach o, $(_NATIVE_LIB_OBJS), $(NATIVE_LIB_OBJDIR)/$o)
NATIVE_LIB_HEADERS=$(shell find $(NATIVE_LIB_INCLUDEDIR) -name "*.h" -type f)

$(NATIVE_LIB_OBJDIR)/%.o: $(NATIVE_LIB_SRCDIR)/%.c $(NATIVE_LIB_HEADERS)
	mkdir -p $(@D)
	$(NATIVE_CC) -c $(NATIVE_CFLAGS) $< -o $@

